Set LC_ALL and LANG when starting octoprint
Fixes errors from Click about ASCII encoding:

    RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment
    This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the follow
        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8